Nomes dos integrantes: Adrian de Almeida Silva - RA: 821146774 Fernando Su Jia Jie - RA: 821162482 Luiz Carlos Chirutti - RA: 821269633 Marcelo Miguel Ferreira - RA: 821159191 Victor Dias De Araujo Braga - RA: 821148935


Alguns dos códigos podem demorar mais de uma hora para rodar, colocarei um comentário nesses códigos. Mas, felizmente eles podem ser ignorados pois servem apenas para achar os melhores parâmetros internos para nossos classificadores.


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving death-rates-from-air-pollution.csv to death-rates-from-air-pollution.csv


# Normalizando os dados

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
dados = pd.read_csv('death-rates-from-air-pollution.csv')

In [ ]:
Paises =["South Africa", "Angola", "Algeria", "Benin", "Botswana", "Burkina Faso", "Burundi", "Cape Verde", "Cameroon",
              "Chad", "Comoros", "Congo", "Côte d'ivoire", "Djibouti", "Egypt", "Eritrea", "Ethiopia", "Gabon",
              "Gambia", "Ghana", "Guinea", "Guinea-Bissau", "Equatorial Guinea", "Lesotho", "Liberia", "Libya", "Madagascar",
              "Malawi", "Mali", "Morocco", "Mauritius", "Mauritania", "Mozambique", "Namibia", "Niger", "Nigeria", "Kenya",
              "Central African Republic", "Democratic Republic of Congo", "Rwanda", "Sao Tome and Principe", "Senegal",
              "Sierra Leone", "Seychelles", "Tunisia", "Somalia", "Swaziland", "Sudan", "South Sudan", "Uganda", "Tanzania",
              "Togo", "Zambia", "Zimbabwe","Australia", "Fiji", "Marshall Islands", "Solomon Islands", "Kiribati", "Micronesia (country)",
              "New Zealand", "Papua New Guinea", "Samoa", "Tonga", "Vanuatu","Afghanistan", "Saudi Arabia", "Bangladesh", "Bahrain", "Brunei",
              "Bhutan", "Cambodia", "Qatar", "Kazakhstan", "China", "Singapore", "North Korea", "South Korea",
             "United Arab Emirates", "Philippines", "Yemen","India", "Indonesia", "Iran", "Iraq", "Israel", "Japan", "Jordan",
             "Kuwait", "Laos", "Lebanon", "Malaysia", "Maldives",
             "Myanmar", "Mongolia", "Nepal", "Oman", "Pakistan", "Kyrgyzstan", "Syria", "Sri Lanka",
              "Tajikistan", "Thailand", "Timor", "Turkey", "Turkmenistan", "Uzbekistan",
             "Vietnam","Albania", "Germany", "Andorra", "Armenia", "Austria", "Azerbaijan", "Belarus", "Belgium", "Bosnia and Herzegovina",
             "Bulgaria","Cyprus", "Croatia", "Denmark", "Slovakia", "Slovenia", "Spain", "Estonia", "Finland", "France", "Georgia",
            "Greece", "Hungary", "Ireland","Iceland", "Italy", "Latvia", "Lithuania", "Luxembourg", "Macedonia", "Malta", "Moldova",
            "Montenegro", "Norway", "Netherlands", "Poland", "Portugal",
            "England", "Czech Republic", "Romania", "Russia", "Serbia", "Sweden", "Switzerland", "Ukraine",
            "Antigua and Barbuda", "Argentina", "Bahamas","Barbados","Belize", "Bolivia",
             "Brazil", "Canada", "Chile", "Colombia", "Costa Rica","Cuba", "Dominica", "El Salvador",
             "Ecuador", "United States", "Grenada", "Guatemala", "Guyana", "Haiti", "Honduras",
             "Jamaica", "Mexico", "Nicaragua", "Panama", "Paraguay", "Peru", "Dominican Republic",
             "Saint Lucia", "Saint Vincent and the Grenadines", "Suriname", "Trinidad and Tobago", "Uruguay", "Venezuela", "American Samoa", "Bermuda",
         "Cote d'Ivoire", "Puerto Rico", "Scotland", "Taiwan", "United Kingdom", "Wales", "Andean Latin America", "Australasia", "Caribbean", "Central Asia",
         "Central Europe, Eastern Europe, and Central Asia" , "Central Sub-Saharan Africa", "Central Latin America", "East Asia", "Eastern Europe",
         "Eastern Sub-Saharan Africa", "Guam", "North Africa and Middle East", "North America", "Northern Ireland", "Northern Mariana Islands", "Oceania",
         "Palestine", "South Asia", "Southeast Asia", "Southeast Asia, East Asia, and Oceania", "Southern Latin America", "Southern Sub-Saharan Africa",
         "Sub-Saharan Africa", "Tropical Latin America", "United States Virgin Islands", "Western Europe", "Western Sub-Saharan Africa"]

In [ ]:
#Oceania
CountOce = ["Australia", "Fiji", "Marshall Islands", "Solomon Islands", "Kiribati", "Micronesia (country)",
            "New Zealand", "Papua New Guinea", "Samoa", "Tonga", "Vanuatu", "American Samoa", "Australasia",
            "Northern Mariana Islands", "Oceania"]

In [ ]:
#Asia
CountAsia = ["Afghanistan", "Saudi Arabia", "Bangladesh", "Bahrain", "Brunei", "Bhutan", "Cambodia", "Qatar", "Kazakhstan", "China", "Singapore", "North Korea", "South Korea",
             "United Arab Emirates", "Philippines", "Yemen","India", "Indonesia", "Iran", "Iraq", "Israel", "Japan", "Jordan", "Kuwait", "Laos", "Lebanon", "Malaysia", "Maldives",
             "Myanmar", "Mongolia", "Nepal", "Oman", "Pakistan", "Kyrgyzstan", "Syria", "Sri Lanka", "Tajikistan", "Thailand", "Timor", "Turkey", "Turkmenistan", "Uzbekistan",
             "Vietnam", "Taiwan", "Central Asia", "East Asia", "Palestine", "South Asia", "Southeast Asia", "Southeast Asia, East Asia, and Oceania"]

In [ ]:
#Europa
CountEur = ["Albania", "Germany", "Andorra", "Armenia", "Austria", "Azerbaijan", "Belarus", "Belgium", "Bosnia and Herzegovina", "Bulgaria",
            "Cyprus", "Croatia", "Denmark", "Slovakia", "Slovenia", "Spain", "Estonia", "Finland", "France", "Georgia", "Greece", "Hungary", "Ireland",
            "Iceland", "Italy", "Latvia", "Lithuania", "Luxembourg", "Macedonia", "Malta", "Moldova", "Montenegro", "Norway", "Netherlands", "Poland", "Portugal",
            "England", "Czech Republic", "Romania", "Russia", "Serbia", "Sweden", "Switzerland", "Ukraine", "Scotland", "United Kingdom", "Wales",
            "Central Europe", "Central Europe, Eastern Europe, and Central Asia", "Eastern Europe", "Northern Ireland", "Western Europe", 
            ]

In [ ]:
#America
CountAmer = ["Antigua and Barbuda", "Argentina", "Bahamas","Barbados","Belize", "Bolivia",
             "Brazil", "Canada", "Chile", "Colombia", "Costa Rica","Cuba", "Dominica", "El Salvador",
             "Ecuador", "United States", "Grenada", "Guatemala", "Guyana", "Haiti", "Honduras",
             "Jamaica", "Mexico", "Nicaragua", "Panama", "Paraguay", "Peru", "Dominican Republic",
             "Saint Lucia", "Saint Vincent and the Grenadines", "Suriname", "Trinidad and Tobago", "Uruguay", "Venezuela", "Bermuda", "Puerto Rico",
             "Andean Latin America", "Caribbean", "Central Latin America", "Guam", "North America", "Southern Latin America", "Southern Sub-Saharan Africa",
             "Tropical Latin America", "United States Virgin Islands"]

In [ ]:
#Africa
CountAfrica = ["South Africa", "Angola", "Algeria", "Benin", "Botswana", "Burkina Faso", "Burundi", "Cape Verde", "Cameroon",
              "Chad", "Comoros", "Congo", "Côte d'ivoire", "Djibouti", "Egypt", "Eritrea", "Ethiopia", "Gabon",
              "Gambia", "Ghana", "Guinea", "Guinea-Bissau", "Equatorial Guinea", "Lesotho", "Liberia", "Libya", "Madagascar",
              "Malawi", "Mali", "Morocco", "Mauritius", "Mauritania", "Mozambique", "Namibia", "Niger", "Nigeria", "Kenya",
              "Central African Republic", "Democratic Republic of Congo", "Rwanda", "Sao Tome and Principe", "Senegal",
              "Sierra Leone", "Seychelles", "Tunisia", "Somalia", "Swaziland", "Sudan", "South Sudan", "Uganda", "Tanzania",
              "Togo", "Zambia", "Zimbabwe", "Cote d'Ivoire" , "Central Sub-Saharan Africa", "Eastern Sub-Saharan Africa", 
               "North Africa and Middle East", "Sub-Saharan Africa","Western Sub-Saharan Africa"]

In [ ]:
def continent(pais):
  if pais in CountEur:
    return 'Europa'
  elif pais in CountAmer:
    return 'America'
  elif pais in CountAsia:
    return 'Asia'
  elif pais in CountOce:
    return 'Oceania'
  elif pais in CountAfrica:
    return 'Africa'
  else:
    return 'na'

In [ ]:
dados['Continente'] = dados['Entity'].apply(continent)

In [ ]:
dados['Continente'].value_counts()

Africa     1652
Europa     1456
Asia       1400
America    1260
Oceania     420
na          280
Name: Continente, dtype: int64

In [ ]:
dados.drop(dados.loc[dados['Continente'] == 'na'].index,inplace=True)

#Selecionando as décadas

Selecionando dados dos anos 90's

In [ ]:
d90s = dados.loc[(dados['Year']>=1991)&(dados['Year']<=2000)]

Sepando os dados e a variável target

In [ ]:
X = d90s[['Air pollution (total) (deaths per 100,000)','Indoor air pollution (deaths per 100,000)',
           'Outdoor particulate matter (deaths per 100,000)','Outdoor ozone pollution (deaths per 100,000)']]

In [ ]:
y = d90s[['Continente']]

Selecionando dados dos anos 00's

In [ ]:
d00s = dados.loc[(dados['Year']>=2001)&(dados['Year']<=2010)]

Sepando os dados e a variável target

In [ ]:
X00 = d00s[['Air pollution (total) (deaths per 100,000)','Indoor air pollution (deaths per 100,000)',
           'Outdoor particulate matter (deaths per 100,000)','Outdoor ozone pollution (deaths per 100,000)']]

In [ ]:
y00 = d00s[['Continente']]

#Separando os dados em treino e teste

In [ ]:
from sklearn.model_selection import train_test_split
import sklearn.metrics as metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [ ]:
X_train90, X_test90, y_train90, y_test90 = train_test_split(X,y, test_size=0.3,random_state=42)

In [ ]:
X_train00, X_test00, y_train00, y_test00 = train_test_split(X00,y00, test_size=0.3,random_state=10)

# Árvore de decisão

Àrvore 90s

In [ ]:
from sklearn import tree
modeloARV90 = tree.DecisionTreeClassifier(criterion='entropy', max_depth=15)
modeloARV90 = modeloARV90.fit(X_train90, y_train90)
predictionsARV90 = modeloARV90.predict(X_test90)

In [ ]:
confARV90 = confusion_matrix(predictionsARV90,y_test90)

In [ ]:
print("Acurácia do modelo Árvore de decisão década 90s, foi de", round(accuracy_score(y_test90, predictionsARV90)*100,2),"%.",
      "\nMatriz de confusão do modelo Árvore de decisão, década 90s:\n",confARV90)

Acurácia do modelo Árvore de decisão década 90s, foi de 88.08 %. 
Matriz de confusão do modelo Árvore de decisão, década 90s:
 [[164   3  12   5   2]
 [ 14 124   1   2   1]
 [  6   2 124  14   0]
 [  4   6   6 131   0]
 [  0   0   0   1  41]]


Árvore 00s

In [ ]:
modeloARV00 = tree.DecisionTreeClassifier(criterion='entropy', max_depth=15)
modeloARV00 = modeloARV00.fit(X_train00, y_train00)
predictionsARV00 = modeloARV00.predict(X_test00)

In [ ]:
confARV00 = confusion_matrix(predictionsARV00,y_test00)

In [ ]:
print("Acurácia do modelo Árvore de decisão, década 00s, foi de", round(accuracy_score(y_test00, predictionsARV00)*100,2),"%.",
      "\nMatriz de confusão do modelo Árvore de decisão, década 00s:\n",confARV00)

Acurácia do modelo Árvore de decisão, década 00s, foi de 90.65 %. 
Matriz de confusão do modelo Árvore de decisão, década 00s:
 [[176   3   8   2   0]
 [  3 118  10   4   1]
 [  2  10 123  10   0]
 [  3   6   0 145   0]
 [  0   0   0   0  39]]


#Naive Bayes da Década de 90

Criando o modelo Naive Bayes Gaussiano

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [ ]:
modeloGau = GaussianNB()

Achando os melhores parâmetros

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
paramG = {'var_smoothing':[-1,1e-20,1e-17,1e-15,1e-14,1e-13,1e-12,1e-11,1e-10,1e-9,1e-8,1]}

In [ ]:
grid1 = GridSearchCV(modeloGau,paramG)

In [ ]:
grid1.fit(X_train90,y_train90.values.ravel())

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:489: RuntimeWarning: invalid value encountered in log
  n_ij = -0.5 * np.sum(np.log(2.0 * np.pi * self.var_[i, :]))
/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:489: RuntimeWarning: invalid value encountered in log
  n_ij = -0.5 * np.sum(np.log(2.0 * np.pi * self.var_[i, :]))
/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:489: RuntimeWarning: invalid value encountered in log
  n_ij = -0.5 * np.sum(np.log(2.0 * np.pi * self.var_[i, :]))
/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:489: RuntimeWarning: invalid value encountered in log
  n_ij = -0.5 * np.sum(np.log(2.0 * np.pi * self.var_[i, :]))
/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:489: RuntimeWarning: invalid value encountered in log
  n_ij = -0.5 * np.sum(np.log(2.0 * np.pi * self.var_[i, :]))


GridSearchCV(estimator=GaussianNB(),
             param_grid={'var_smoothing': [-1, 1e-20, 1e-17, 1e-15, 1e-14,
                                           1e-13, 1e-12, 1e-11, 1e-10, 1e-09,
                                           1e-08, 1]})

In [ ]:
grid1.best_estimator_

GaussianNB(var_smoothing=1e-20)

Aplicando o melhor parâmetro

In [ ]:
modeloGau_o = GaussianNB(var_smoothing=1e-20)

In [ ]:
modeloGau_o.fit(X_train90,y_train90.values.ravel())

GaussianNB(var_smoothing=1e-20)

In [ ]:
preditoG = modeloGau_o.predict(X_test90)

Matriz de confusão, modelo Naive Bayes Gaussiano década 90's

In [ ]:
confG = confusion_matrix(y_test90,preditoG)

In [ ]:
print("Acurácia do modelo Naive Bayes Gaussiano década 90s, foi de", round(accuracy_score(y_test90, preditoG),2)*100,
                                                                      "%\nMatriz de confusão modelo Naive Bayes Gaussiano década 90s:\n",confG)

Acurácia do modelo Naive Bayes Gaussiano década 90s, foi de 66.0 %
Matriz de confusão modelo Naive Bayes Gaussiano década 90s:
 [[141   7   5  28   7]
 [  6  94   2  33   0]
 [ 28  11  59  45   0]
 [  1  20   6 126   0]
 [ 11  14   0   4  15]]


Classificador Multinomial Naive Bayes

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
modeloM = MultinomialNB()

Achando os melhores parâmetros

In [ ]:
paramM = {'alpha': (10,5,2,1, 0.1, 0.01, 0.001, 0.0001, 0.00001)  }  

In [ ]:
grid2 = GridSearchCV(modeloM,paramM)

In [ ]:
grid2.fit(X_train90,y_train90.values.ravel())

GridSearchCV(estimator=MultinomialNB(),
             param_grid={'alpha': (10, 5, 2, 1, 0.1, 0.01, 0.001, 0.0001,
                                   1e-05)})

In [ ]:
grid2.best_estimator_

MultinomialNB(alpha=0.1)

Aplicando o melhor parâmetro

In [ ]:
modeloM_o = MultinomialNB(alpha=1)

In [ ]:
modeloM_o.fit(X_train90,y_train90.values.ravel())

MultinomialNB(alpha=1)

In [ ]:
preditoM = modeloM_o.predict(X_test90)

Matriz de confusão do modelo Multinomial Naive Bayes, década 90s

In [ ]:
confM = confusion_matrix(y_test90,preditoM)

In [ ]:
print("Acurácia do modelo Naive Bayes Multinomial década 90s, foi de", round(accuracy_score(y_test90, preditoM)*100,2),"%.",
      "\nMatriz de confusão modelo Naive Bayes Multinomial década 90s:\n",confM)

Acurácia do modelo Naive Bayes Multinomial década 90s, foi de 52.34 %. 
Matriz de confusão modelo Naive Bayes Multinomial década 90s:
 [[116   7   1  27  37]
 [ 18  45  15  57   0]
 [ 29   8  39  60   7]
 [  3  18   4 128   0]
 [  9   3   2  11  19]]




Classificador Naive Bayes Bernoulli


In [ ]:
from sklearn.naive_bayes import BernoulliNB

In [ ]:
modeloB = BernoulliNB()

Achando os melhores parâmetros

In [ ]:
paramB = {'alpha': [-10, -5,0.000001,0.00001,0.0001,0.001,0.005,0.01, 0.1, 0.5, 1.0, 10.0], 'binarize':[-10,-5,1,5,10,25,50,75,100,500]}

In [ ]:
grid3 = GridSearchCV(modeloB,paramB)

In [ ]:
grid3.fit(X_train90,y_train90.values.ravel())

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
100 fits failed out of a total of 600.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
50 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py", line 691, in fit
    alpha = self._check_alpha()
  File "/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py", line 547, in _check_alpha
    % np.min(self.alpha)
ValueError: Smoothing parameter alpha = -1.0e+01. alpha should be > 0.



GridSearchCV(estimator=BernoulliNB(),
             param_grid={'alpha': [-10, -5, 1e-06, 1e-05, 0.0001, 0.001, 0.005,
                                   0.01, 0.1, 0.5, 1.0, 10.0],
                         'binarize': [-10, -5, 1, 5, 10, 25, 50, 75, 100, 500]})

In [ ]:
grid3.best_estimator_

BernoulliNB(alpha=1e-06, binarize=50)

Aplicando o melhor parâmetro

In [ ]:
modeloB_o = BernoulliNB(alpha=1e-06, binarize=50)

In [ ]:
modeloB_o.fit(X_train90,y_train90)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BernoulliNB(alpha=1e-06, binarize=50)

In [ ]:
preditoB = modeloB_o.predict(X_test90)



Matriz de confusão do modelo Bernoulli Naive Bayes, década 90s


In [ ]:
confB = confusion_matrix(preditoB,y_test90)

In [ ]:
print("Acurácia do modelo Naive Bayes Bernoulli década 90s, foi de", round(accuracy_score(y_test90, preditoB)*100,2),"%.",
      "\nMatriz de confusão do modelo Naive Bayes Bernoulli década 90s:\n",confB)

Acurácia do modelo Naive Bayes Bernoulli década 90s, foi de 55.51 %. 
Matriz de confusão do modelo Naive Bayes Bernoulli década 90s:
 [[156  14  45   4  28]
 [ 10  57  10  24   5]
 [ 22   5  72  42   0]
 [  0  59  16  83  11]
 [  0   0   0   0   0]]


#Naive Bayes da Década de 00s

Criando o modelo Naive Bayes Gaussiano

In [ ]:
modeloGau00 = GaussianNB()

Achando os melhores parâmetros

In [ ]:
paramG00 = {'var_smoothing':[-1,1e-20,1e-17,1e-15,1e-14,1e-13,1e-12,1e-11,1e-10,1e-9,1e-8,1]}

In [ ]:
grid4 = GridSearchCV(modeloGau00,paramG00)

In [ ]:
grid4.fit(X_train00,y_train00.values.ravel())

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:489: RuntimeWarning: invalid value encountered in log
  n_ij = -0.5 * np.sum(np.log(2.0 * np.pi * self.var_[i, :]))
/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:489: RuntimeWarning: invalid value encountered in log
  n_ij = -0.5 * np.sum(np.log(2.0 * np.pi * self.var_[i, :]))
/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:489: RuntimeWarning: invalid value encountered in log
  n_ij = -0.5 * np.sum(np.log(2.0 * np.pi * self.var_[i, :]))
/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:489: RuntimeWarning: invalid value encountered in log
  n_ij = -0.5 * np.sum(np.log(2.0 * np.pi * self.var_[i, :]))
/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:489: RuntimeWarning: invalid value encountered in log
  n_ij = -0.5 * np.sum(np.log(2.0 * np.pi * self.var_[i, :]))


GridSearchCV(estimator=GaussianNB(),
             param_grid={'var_smoothing': [-1, 1e-20, 1e-17, 1e-15, 1e-14,
                                           1e-13, 1e-12, 1e-11, 1e-10, 1e-09,
                                           1e-08, 1]})

In [ ]:
grid4.best_estimator_

GaussianNB(var_smoothing=1e-20)

Aplicando o melhor parâmetro

In [ ]:
modeloGau_o00 = GaussianNB(var_smoothing=1e-20)

In [ ]:
modeloGau_o00.fit(X_train00,y_train00)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(var_smoothing=1e-20)

In [ ]:
preditoG00 = modeloGau_o00.predict(X_test00)

Matriz de confusão, modelo Naive Bayes Gaussiano década 00's

In [ ]:
confG00 = confusion_matrix(y_test00,preditoG00)

In [ ]:
print("Acurácia do modelo Naive Bayes Gaussiano década 00s, foi de", round(accuracy_score(y_test00, preditoG00)*100,2),"%.",
      "\nMatriz de confusão modelo Naive Bayes Gaussiano década 00s:\n",confG00)

Acurácia do modelo Naive Bayes Gaussiano década 00s, foi de 65.16 %. 
Matriz de confusão modelo Naive Bayes Gaussiano década 00s:
 [[149   5  13  14   3]
 [  9  83   4  41   0]
 [ 28  12  58  43   0]
 [  6  18   7 130   0]
 [  8  15   2   3  12]]


Classificador Multinomial Naive Bayes

In [ ]:
modeloM00 = MultinomialNB()

Achando os melhores parâmetros

In [ ]:
paramM00 = {'alpha': (10,5,2,1, 0.1, 0.01, 0.001, 0.0001, 0.00001)  }  

In [ ]:
grid5 = GridSearchCV(modeloM00,paramM00)

In [ ]:
grid5.fit(X_train00,y_train00.values.ravel())

GridSearchCV(estimator=MultinomialNB(),
             param_grid={'alpha': (10, 5, 2, 1, 0.1, 0.01, 0.001, 0.0001,
                                   1e-05)})

In [ ]:
grid5.best_estimator_

MultinomialNB(alpha=2)

Aplicando o melhor parâmetro

In [ ]:
modeloM_o00 = MultinomialNB(alpha=2)

In [ ]:
modeloM_o00.fit(X_train00,y_train00)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB(alpha=2)

In [ ]:
preditoM00 = modeloM_o00.predict(X_test00)

Matriz de confusão do modelo Multinomial Naive Bayes, década 00s

In [ ]:
confM00 = confusion_matrix(y_test00,preditoM00)

In [ ]:
print("Acurácia do modelo Naive Bayes Multinomial década 00s, foi de", round(accuracy_score(y_test00, preditoM00)*100,2),"%.",
      "\nMatriz de confusão modelo Naive Bayes Multinomial década 00s:\n",confM00)

Acurácia do modelo Naive Bayes Multinomial década 00s, foi de 48.27 %. 
Matriz de confusão modelo Naive Bayes Multinomial década 00s:
 [[ 94   7   6  18  59]
 [ 16  32  17  70   2]
 [ 28   7  51  52   3]
 [  2  19  11 129   0]
 [  6   4   6  10  14]]




Classificador Naive Bayes Bernoulli


In [ ]:
modeloB00 = BernoulliNB()

Achando os melhores parâmetros

In [ ]:
paramB00 = {'alpha': [-10, -5,0.000001,0.00001,0.0001,0.001,0.005,0.01, 0.1, 0.5, 1.0, 10.0], 'binarize':[-10,-5,1,5,10,25,50,75,100,500]}

In [ ]:
grid6 = GridSearchCV(modeloB00,paramB00)

In [ ]:
grid6.fit(X_train00,y_train00.values.ravel())

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
100 fits failed out of a total of 600.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
50 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py", line 691, in fit
    alpha = self._check_alpha()
  File "/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py", line 547, in _check_alpha
    % np.min(self.alpha)
ValueError: Smoothing parameter alpha = -1.0e+01. alpha should be > 0.



GridSearchCV(estimator=BernoulliNB(),
             param_grid={'alpha': [-10, -5, 1e-06, 1e-05, 0.0001, 0.001, 0.005,
                                   0.01, 0.1, 0.5, 1.0, 10.0],
                         'binarize': [-10, -5, 1, 5, 10, 25, 50, 75, 100, 500]})

In [ ]:
grid3.best_estimator_

BernoulliNB(alpha=1e-06, binarize=50)

Aplicando o melhor parâmetro

In [ ]:
modeloB_o00 = BernoulliNB(alpha=1e-06, binarize=50)

In [ ]:
modeloB_o00.fit(X_train00,y_train00)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BernoulliNB(alpha=1e-06, binarize=50)

In [ ]:
preditoB00 = modeloB_o00.predict(X_test00)

Matriz de confusão do modelo Bernoulli Naive Bayes, década 00s


In [ ]:
confB00 = confusion_matrix(preditoB00,y_test00)

In [ ]:
print("Acurácia do modelo  Bernoulli Naive Bayes década 00s, foi de", round(accuracy_score(y_test00, preditoB00)*100,2),"%.",
      "\nMatriz de confusão modelo  Bernoulli Naive Bayes década 00s:\n",confB00)

Acurácia do modelo  Bernoulli Naive Bayes década 00s, foi de 52.64 %. 
Matriz de confusão modelo  Bernoulli Naive Bayes década 00s:
 [[153  13  41   1  20]
 [  0   0   0   0   0]
 [ 20   7  61  25   0]
 [ 11 117  39 135  20]
 [  0   0   0   0   0]]


#SVM da Década de 90s

Máquina de Vetores de Suporte (SVM)

In [ ]:
from sklearn.svm import SVC

Classificação Linear das SVM

In [ ]:
svm_l = SVC()

Aplicando o GridSearchCV para achar os melhores parâmetros

In [ ]:
paramSL = {'kernel':['linear'], 'C':[1,5,10,100],'gamma':[1,5,50,100]}

In [ ]:
#Pode ser ignorado
grid7 = GridSearchCV(svm_l,paramSL)

In [ ]:
#Pode se ignorado, pois demorou 1 hora para processar
grid7.fit(X_train90,y_train90.values.ravel())

GridSearchCV(estimator=SVC(),
             param_grid={'C': [1, 5, 10, 100], 'gamma': [1, 5, 50, 100],
                         'kernel': ['linear']})

In [ ]:
#Pode ser ignorado
grid7.best_estimator_

SVC(C=100, gamma=1, kernel='linear')

Aplicando o melhor parâmetro

In [ ]:
svm_l_o = SVC(C=10, gamma=1, kernel='linear')

In [ ]:
svm_l_o.fit(X_train90,y_train90)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=10, gamma=1, kernel='linear')

In [ ]:
preditoS_l = svm_l_o.predict(X_test90)

Matriz de confusão do modelo SVM Linear

In [ ]:
confS_l = confusion_matrix(y_test90,preditoS_l)

In [ ]:
print("Acurácia do modelo  SVM Linear década 90s, foi de", round(accuracy_score(y_test90, preditoS_l)*100,2),"%.",
      "\nMatriz de confusão modelo  SVM Linear década 90s:\n",confS_l)

Acurácia do modelo  SVM Linear década 90s, foi de 69.83 %. 
Matriz de confusão modelo  SVM Linear década 90s:
 [[138  13  31   4   2]
 [  7  94   4  30   0]
 [ 14  10  84  31   4]
 [  0  18  13 122   0]
 [  3  12   0   4  25]]


Classificação SVM Kernel Polinomial

In [ ]:
svm_p = SVC()

Aplicando o GridSearchCV para achar os melhores parâmetros


In [ ]:
paramSP = {'kernel':['poly'],'degree':[1,2,4,3,5,6,7,8]}

In [ ]:
#Pode ser ignorado
grid8 = GridSearchCV(svm_p,paramSP)

In [ ]:
#Pode ser ignorado, pois 15 minutos para processar
grid8.fit(X_train90,y_train90.values.ravel())

GridSearchCV(estimator=SVC(),
             param_grid={'degree': [1, 2, 4, 3, 5, 6, 7, 8],
                         'kernel': ['poly']})

In [ ]:
#Pode ser ignorado
grid8.best_estimator_

SVC(degree=1, kernel='poly')

Aplicando o melhor parâmetro

In [ ]:
svm_p_o = SVC(degree=1, kernel='poly')

In [ ]:
svm_p_o.fit(X_train90,y_train90)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(degree=1, kernel='poly')

In [ ]:
preditoS_p = svm_p_o.predict(X_test90)

Matriz de confusão do modelo SVM Polinomial

In [ ]:
confS_p = confusion_matrix(y_test90,preditoS_p)

In [ ]:
print("Acurácia do modelo SVM Polinomial década 90s, foi de", round(accuracy_score(y_test90, preditoS_p)*100,2),"%.",
      "\nMatriz de confusão modelo SVM Polinomial década 90s:\n",confS_p)

Acurácia do modelo SVM Polinomial década 90s, foi de 57.01 %. 
Matriz de confusão modelo SVM Polinomial década 90s:
 [[144   8  14  22   0]
 [  6  45   7  77   0]
 [ 23  13  72  35   0]
 [  0   7  29 117   0]
 [ 23   7   0  14   0]]




Classificação SVM Kernel RBF Gaussiano

In [ ]:
svm_r = SVC()

Aplicando o GridSearchCV para achar os melhores parâmetros

In [ ]:
paramSR = {'kernel':['rbf'],'C':[1,2,5,8,10,15,20,30,50,75,100],'gamma':[0.00001,0.0001,0.001,0.01,0.1,1,2,3,5,50,100]}

In [ ]:
grid8 = GridSearchCV(svm_r,paramSR)

In [ ]:
grid8.fit(X_train90,y_train90.values.ravel())

GridSearchCV(estimator=SVC(),
             param_grid={'C': [1, 2, 5, 8, 10, 15, 20, 30, 50, 75, 100],
                         'gamma': [1e-05, 0.0001, 0.001, 0.01, 0.1, 1, 2, 3, 5,
                                   50, 100],
                         'kernel': ['rbf']})

In [ ]:
grid8.best_estimator_

SVC(C=100, gamma=0.01)

Aplicando o melhor parâmetro

In [ ]:
svm_r_o = SVC(C=100, gamma=0.01)

In [ ]:
svm_r_o.fit(X_train90,y_train90)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=100, gamma=0.01)

In [ ]:
preditoS_r = svm_r_o.predict(X_test90)

Matriz de confusão do modelo SVM RBF Gaussiano

In [ ]:
confS_r = confusion_matrix(y_test90,preditoS_r)

In [ ]:
print("Acurácia do modelo SVM RBF Gaussiano década 90s, foi de", round(accuracy_score(y_test90, preditoS_r)*100,2),"%.",
      "\nMatriz de confusão modelo  SVM RBF Gaussiano década 90s:\n",confS_r)

Acurácia do modelo SVM RBF Gaussiano década 90s, foi de 87.78 %. 
Matriz de confusão modelo  SVM RBF Gaussiano década 90s:
 [[165   8  11   1   3]
 [  7 119   3   5   1]
 [ 14   3 119   7   0]
 [  8   3   4 138   0]
 [  2   1   0   0  41]]


#SVM da Décade 00s

Classificação Linear das SVM

In [ ]:
svm_l00 = SVC()

Aplicando o GridSearchCV para achar os melhores parâmetros

In [ ]:
paramSL00 = {'kernel':['linear'], 'C':[1,5,10,100],'gamma':[1,5,50,100]}

In [ ]:
#Pode ser ignorado
grid9 = GridSearchCV(svm_l00,paramSL00)

In [ ]:
#Pode ser ignorado, pois demorou 47 minutos para processar
grid9.fit(X_train00,y_train00.values.ravel())

In [ ]:
#Pode ser ignorado
grid9.best_estimator_

Aplicando o melhor parâmetro

In [ ]:
svm_l_o00 = SVC(C=100, gamma=1, kernel='linear')

In [ ]:
svm_l_o00.fit(X_train00,y_train00)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=100, gamma=1, kernel='linear')

In [ ]:
preditoS_l00 = svm_l_o00.predict(X_test00)

Matriz de confusão do modelo SVM Linear

In [ ]:
confS_l00 = confusion_matrix(y_test00,preditoS_l00)

In [ ]:
print("Acurácia do modelo SVM Linear década 00s, foi de", round(accuracy_score(y_test00, preditoS_l00)*100,2),"%.",
      "\nMatriz de confusão modelo SVM Linear década 00s:\n",confS_l00)

Acurácia do modelo SVM Linear década 00s, foi de 68.63 %. 
Matriz de confusão modelo SVM Linear década 00s:
 [[156   4  21   3   0]
 [ 15  82   8  32   0]
 [ 32  11  74  24   0]
 [  3  19  14 125   0]
 [  2  14   0   6  18]]




Classificação SVM Kernel Polinomial


In [ ]:
svm_p00 = SVC()

Aplicando o GridSearchCV para achar os melhores parâmetros


In [ ]:
paramSP00 = {'kernel':['poly'],'degree':[1,2,4,3,5,6,7,8]}

In [ ]:
#Pode ser ignorado
grid10 = GridSearchCV(svm_p00,paramSP00)

In [ ]:
#Pode ser ignorado, pois demorou 3 minutos para rodar
grid10.fit(X_train00,y_train00.values.ravel())

GridSearchCV(estimator=SVC(),
             param_grid={'degree': [1, 2, 4, 3, 5, 6, 7, 8],
                         'kernel': ['poly']})

In [ ]:
#Pode ser ignorado
grid10.best_estimator_

SVC(degree=5, kernel='poly')

Aplicando o melhor parâmetro

In [ ]:
svm_p_o00 = SVC(degree=5, kernel='poly')

In [ ]:
svm_p_o00.fit(X_train00,y_train00)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(degree=5, kernel='poly')

In [ ]:
preditoS_p00 = svm_p_o00.predict(X_test00)

Matriz de confusão do modelo SVM Polinomial

In [ ]:
confS_p00 = confusion_matrix(y_test00,preditoS_p00)

In [ ]:
print("Acurácia do modelo SVM Kernel Polinomial década 00s, foi de", round(accuracy_score(y_test00, preditoS_p00)*100,2),"%.",
      "\nMatriz de confusão modelo SVM Kernel Polinomial década 00s:\n",confS_p00)

Acurácia do modelo SVM Kernel Polinomial década 00s, foi de 56.56 %. 
Matriz de confusão modelo SVM Kernel Polinomial década 00s:
 [[155   3   2  24   0]
 [  8   6   0 123   0]
 [ 31   4  55  51   0]
 [  9   1   5 146   0]
 [  4   3   0  20  13]]


Classificação SVM Kernel RBF Gaussiano

In [ ]:
svm_r00 = SVC()

Aplicando o GridSearchCV para achar os melhores parâmetros

In [ ]:
paramSR00 = {'kernel':['rbf'],'C':[1,2,5,8,10,15,20,30,50,75,100],'gamma':[0.00001,0.0001,0.001,0.01,0.1,1,2,3,5,50,100]}

In [ ]:
grid11 = GridSearchCV(svm_r00,paramSR00)

In [ ]:
grid11.fit(X_train00,y_train00.values.ravel())

GridSearchCV(estimator=SVC(),
             param_grid={'C': [1, 2, 5, 8, 10, 15, 20, 30, 50, 75, 100],
                         'gamma': [1e-05, 0.0001, 0.001, 0.01, 0.1, 1, 2, 3, 5,
                                   50, 100],
                         'kernel': ['rbf']})

In [ ]:
grid11.best_estimator_

SVC(C=100, gamma=0.01)

Aplicando o melhor parâmetro

In [ ]:
svm_r_o00 = SVC(C=100, gamma=0.01)

In [ ]:
svm_r_o00.fit(X_train00,y_train00)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=100, gamma=0.01)

In [ ]:
preditoS_r00 = svm_r_o00.predict(X_test00)

Matriz de confusão do modelo SVM RBF Gaussiano

In [ ]:
confS_r00 = confusion_matrix(y_test00,preditoS_r00)

In [ ]:
print("Acurácia do modelo SVM RBF Gaussiano década 00s, foi de", round(accuracy_score(y_test00, preditoS_r00)*100,2),"%.",
      "\nMatriz de confusão modelo  SVM RBF Gaussiano década 00s:\n",confS_r00)

Acurácia do modelo SVM RBF Gaussiano década 00s, foi de 85.07 %. 
Matriz de confusão modelo  SVM RBF Gaussiano década 00s:
 [[166   4   8   0   6]
 [  6 112   4  15   0]
 [ 14   8 107  12   0]
 [  4  10   8 139   0]
 [  0   0   0   0  40]]


#KNN


Achando o melhor número de vizinhos para a década 90's

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [ ]:
print("Resultados para classificador KNN na década 90's")
for k in [3,5,7,10,33]:
  modelo = KNeighborsClassifier(n_neighbors=k)
  modelo.fit(X_train90,y_train90)
  predito90 = modelo.predict(X_test90)
  conf_mx90 = confusion_matrix(y_test90, predito90) 
  print('Acurácia do modelo com',k,"vizinhos foi de", (round(accuracy_score(y_test90, predito90),2))*100,"%.")
  print("Matriz de confusão detalhada do KNN,considerando",k,"vizinhos:\n",conf_mx90)

Resultados para classificador KNN na década 90's
Acurácia do modelo com 3 vizinhos foi de 80.0 %.
Matriz de confusão detalhada do KNN,considerando 3 vizinhos:
 [[156   9  11   4   8]
 [  7 112   4  11   1]
 [ 17  10 101  15   0]
 [ 12   8   9 124   0]
 [  8   1   0   0  35]]
Acurácia do modelo com 5 vizinhos foi de 78.0 %.
Matriz de confusão detalhada do KNN,considerando 5 vizinhos:
 [[157  10  10   7   4]
 [  6 111   3  13   2]
 [ 21  10  96  16   0]
 [ 10   5  15 123   0]
 [  9   3   1   0  31]]
Acurácia do modelo com 7 vizinhos foi de 75.0 %.
Matriz de confusão detalhada do KNN,considerando 7 vizinhos:
 [[151  10  10   8   9]
 [  7 103   3  20   2]
 [ 22   8  98  15   0]
 [ 12   8  17 116   0]
 [ 11   3   1   0  29]]
Acurácia do modelo com 10 vizinhos foi de 73.0 %.
Matriz de confusão detalhada do KNN,considerando 10 vizinhos:
 [[152   9   9  10   8]
 [  5  98   6  25   1]
 [ 22   6  97  18   0]
 [ 11   9  20 113   0]
 [ 11   5   1   0  27]]
Acurácia do modelo com 33 vizinhos foi de

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for exam

Achando o melhor número de vizinhos para a década 00s

In [ ]:
print("Resultados para classificador KNN na década 00's:")
for k in [3,5,7,10,33]:
  modelo = KNeighborsClassifier(n_neighbors=k)
  modelo.fit(X_train00,y_train00)
  predito00 = modelo.predict(X_test00)
  conf_mx00 = confusion_matrix(y_test00, predito00)
  print('Acurácia do modelo com',k,"vizinhos foi de", (round(accuracy_score(y_test00, predito00),2))*100,"%.")
  print("Matriz de confusão detalhada do KNN,considerando",k,"vizinhos:\n",conf_mx00)

Resultados para classificador KNN na década 00's:


/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


Acurácia do modelo com 3 vizinhos foi de 77.0 %.
Matriz de confusão detalhada do KNN,considerando 3 vizinhos:
 [[158   4   9   3  10]
 [ 13 100   6  18   0]
 [ 20   9 102   8   2]
 [ 10  17  17 117   0]
 [  2   2   0   0  36]]
Acurácia do modelo com 5 vizinhos foi de 77.0 %.
Matriz de confusão detalhada do KNN,considerando 5 vizinhos:
 [[163   1   8   4   8]
 [ 12 100   4  21   0]
 [ 20   9  96  14   2]
 [ 10  12  22 117   0]
 [  3   4   0   1  32]]
Acurácia do modelo com 7 vizinhos foi de 74.0 %.
Matriz de confusão detalhada do KNN,considerando 7 vizinhos:
 [[167   1   8   3   5]
 [ 10  90   7  29   1]
 [ 21  14  89  14   3]
 [ 11  14  20 116   0]
 [  3   6   1   1  29]]
Acurácia do modelo com 10 vizinhos foi de 72.0 %.
Matriz de confusão detalhada do KNN,considerando 10 vizinhos:
 [[167   2   9   3   3]
 [ 11  89   7  29   1]
 [ 22  14  86  15   4]
 [ 12  20  17 112   0]
 [  5   6   1   2  26]]


/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for exam

Acurácia do modelo com 33 vizinhos foi de 67.0 %.
Matriz de confusão detalhada do KNN,considerando 33 vizinhos:
 [[147   1  24   8   4]
 [ 11  71   8  47   0]
 [ 15  12  93  17   4]
 [  1  13  22 125   0]
 [ 10   6   1  14   9]]


#Cômite

In [ ]:
tot_amr = 0
tot_eur = 0
tot_asi = 0
tot_oce = 0
tot_afr = 0

dados_br = dados.loc[(dados['Entity'] == 'Brazil') & (dados['Year']==1995)]
dados_br = dados_br[['Air pollution (total) (deaths per 100,000)','Indoor air pollution (deaths per 100,000)',
           'Outdoor particulate matter (deaths per 100,000)','Outdoor ozone pollution (deaths per 100,000)']]
#Árvore de decisão
pred_arv = modeloARV90.predict(dados_br)
print(pred_arv)

#Modelo Naive bayes Gaussiano
pred_modeloGau_o = modeloGau_o.predict(dados_br)
print(pred_modeloGau_o)

#Modelo Naive bayes Multinomial
pred_modeloM_o = modeloM_o.predict(dados_br)

#Modelo Naive bayes Bernoulli
pred_modeloB_o = modeloB_o.predict(dados_br)
print(pred_modeloB_o)

#Modelo SVM Linear
pred_svm_l_o = svm_l_o.predict(dados_br)
print(pred_svm_l_o)

#Modelo SVM Polinomial
pred_svm_p_o = svm_p_o.predict(dados_br)
print(pred_svm_p_o)

#Modelo SVM RBF Gaussiano
pred_svm_r_o = svm_r_o.predict(dados_br)
print(pred_svm_r_o)

#Modelo KNN

modelo_KNN = KNeighborsClassifier(n_neighbors=3)
modelo_KNN.fit(X_train90,y_train90)
predito90 = modelo.predict(X_test90)
pred_modelo_KNN = modelo_KNN.predict(dados_br)
print(pred_modelo_KNN)


['America']
['Europa']
['Asia']
['America']
['Europa']
['America']
['America']
['America']


/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [ ]:
print('Como os nossos dados que rodamos é do Brasil de 1995, por tanto o continente é a "America"\n', ['America'],['Europa'],['Asia'],
      ['America'],['Europa'],['America'],['America'],['America'], '\ntendo um acerto de 62,5%')

Como os nossos dados que rodamos é do Brasil de 1995, por tanto o continente é a "America"
 ['America'] ['Europa'] ['Asia'] ['America'] ['Europa'] ['America'] ['America'] ['America'] 
tendo um acerto de 62,5%
